---
- name: Create 3PAR Domain & Users
  hosts: localhost
  become: yes
  become_user: root
  vars:
    user: bob

    
  tasks:
    - name: install sshpass
      package:
        name: sshpass
        state: present
      become: yes

    - name: Create Domain
      shell: /usr/bin/sshpass -p PTzk5fVt ssh -oStrictHostKeyChecking=no 3paradm@172.16.90.167 "createdomain {{ user }}_domain"
      register: domain

    - name: print domain
      debug:
        msg: "{{ domain }}"

    - name: Create Users
      shell: /usr/bin/sshpass -p PTzk5fVt ssh -oStrictHostKeyChecking=no 3paradm@172.16.90.167 "createuser -c Password1 {{ user }}_user {{ user }}_domain edit"
      register: users

    - name: print users
      debug:
        msg: "{{ users }}"
